{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "5.3.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.30"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.30.jar",
          "url": "spring-test-5.3.30.jar",
          "size": 792430,
          "sha512": "cb9cc25197f563adff630e8491f93d93d12c531ce11b741dbd592b31ac276d7e52819493d4a851a44a7f40ec42919522689435e3985dc6dbbfd0b3c7220f2a3e",
          "sha256": "5fbe84cff44bf09ae2ae332799d0c7c3186ecc8019897fdd84ba8f2ad7f1e0b5",
          "sha1": "c0ba379b5836d6b6217d387988af82eb28a56e50",
          "md5": "e2a36068a72ff64d7c5433d15faafc05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.30"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.30.jar",
          "url": "spring-test-5.3.30.jar",
          "size": 792430,
          "sha512": "cb9cc25197f563adff630e8491f93d93d12c531ce11b741dbd592b31ac276d7e52819493d4a851a44a7f40ec42919522689435e3985dc6dbbfd0b3c7220f2a3e",
          "sha256": "5fbe84cff44bf09ae2ae332799d0c7c3186ecc8019897fdd84ba8f2ad7f1e0b5",
          "sha1": "c0ba379b5836d6b6217d387988af82eb28a56e50",
          "md5": "e2a36068a72ff64d7c5433d15faafc05"
        }
      ]
    }
  ]
}
