{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.7.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.16"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.7.16"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.7.16"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.30"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.7.16.jar",
          "url": "spring-boot-starter-2.7.16.jar",
          "size": 4772,
          "sha512": "cfb99809070d47d8cf0753e285d1eb078fc645411ab0695b9fc11430e8371d2cc4d08f7a27547c0d6477530fecdd2dd7bb55af858f6e4909c882b3c0cbcc026d",
          "sha256": "1525a3cca9f16a5b80f960335d919b0af86314ca28b9bb739dd9db9bf5810dce",
          "sha1": "0f80dbc197a703fbeb1a932a9a57a20d318ea475",
          "md5": "fec726669ac5368ca0d8ca8a3a33403f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.16"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.7.16"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.7.16"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.30"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.7.16.jar",
          "url": "spring-boot-starter-2.7.16.jar",
          "size": 4772,
          "sha512": "cfb99809070d47d8cf0753e285d1eb078fc645411ab0695b9fc11430e8371d2cc4d08f7a27547c0d6477530fecdd2dd7bb55af858f6e4909c882b3c0cbcc026d",
          "sha256": "1525a3cca9f16a5b80f960335d919b0af86314ca28b9bb739dd9db9bf5810dce",
          "sha1": "0f80dbc197a703fbeb1a932a9a57a20d318ea475",
          "md5": "fec726669ac5368ca0d8ca8a3a33403f"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.16.jar",
          "url": "spring-boot-starter-2.7.16.jar",
          "size": 4772,
          "sha512": "cfb99809070d47d8cf0753e285d1eb078fc645411ab0695b9fc11430e8371d2cc4d08f7a27547c0d6477530fecdd2dd7bb55af858f6e4909c882b3c0cbcc026d",
          "sha256": "1525a3cca9f16a5b80f960335d919b0af86314ca28b9bb739dd9db9bf5810dce",
          "sha1": "0f80dbc197a703fbeb1a932a9a57a20d318ea475",
          "md5": "fec726669ac5368ca0d8ca8a3a33403f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.7.16"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.16.jar",
          "url": "spring-boot-starter-2.7.16.jar",
          "size": 4772,
          "sha512": "cfb99809070d47d8cf0753e285d1eb078fc645411ab0695b9fc11430e8371d2cc4d08f7a27547c0d6477530fecdd2dd7bb55af858f6e4909c882b3c0cbcc026d",
          "sha256": "1525a3cca9f16a5b80f960335d919b0af86314ca28b9bb739dd9db9bf5810dce",
          "sha1": "0f80dbc197a703fbeb1a932a9a57a20d318ea475",
          "md5": "fec726669ac5368ca0d8ca8a3a33403f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.7.16"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.16-javadoc.jar",
          "url": "spring-boot-starter-2.7.16-javadoc.jar",
          "size": 4740,
          "sha512": "bc4bf2f92071846e1e2e51422cb6cef7fd7c68572e2700c802d0a31ed74993110eb135003afea85eb4ff6de775d9345f838fa95b9db73be952c26e43f1a42c5d",
          "sha256": "9dd037adff5f03129fe28a8e27ab072f4372d9b78c475673331c0c75427c4d0b",
          "sha1": "3a0cacc3b3a7b8918dc79c46b0f7f9f6dd05dea0",
          "md5": "40ac23e1ea8e2bc797ac6efa84027306"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.16-sources.jar",
          "url": "spring-boot-starter-2.7.16-sources.jar",
          "size": 4739,
          "sha512": "aabbc09a944ad30aecfb6a2b06d28939d545717d2aae721edadc9e2f1b3d10b3ecfaf05c7d1b420d9da63643d25c30558464119d0f89510d4717a8d09cd74f1c",
          "sha256": "05e98fe6b1b487cd5a3acb57f76fe42409b047e5f354b596d3d0838d2a178c37",
          "sha1": "8919955e2dc2e49d52eea06abd5a314130988998",
          "md5": "74dad3474ead09e8786d1c02412cbfed"
        }
      ]
    }
  ]
}
